name: freeze latest

on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML, so you have to quote this string
    # every day
    - cron:  '33 3 * * *'
  
jobs:
  ready-for-stable:
    name: freeze latest
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm --//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}} dist-tag add iobroker.webui@0.20.7 latest
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
